-- Create weather data table
CREATE TABLE weather_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city TEXT NOT NULL,
    date DATE NOT NULL,
    temp_max NUMERIC,
    temp_min NUMERIC,
    temp_avg NUMERIC,
    humidity NUMERIC,
    precipitation NUMERIC,
    wind_speed NUMERIC,
    conditions TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
    
    -- Create a unique constraint on city and date
    CONSTRAINT unique_city_date UNIQUE (city, date)
);
