name: Update Weather Data

on:
  schedule:
    - cron: '0 12 * * *'  # 每天UTC 12:00运行（约当地时间早上8点）
  workflow_dispatch:  # 允许手动触发

jobs:
  update-weather:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests
    
    - name: Update weather data
      run: |
        python canada_weather.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add canada_weather.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update weather data $(date +'%Y-%m-%d')" && git push)
