name: Daily Weather Update

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜12点运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-weather:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests google-cloud-bigquery pandas-gbq
    
    - name: Setup Google Cloud Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
    
    - name: Run weather update script
      env:
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      run: |
        python canada_weather.py
