name: Daily Weather Update

on:
  schedule:
    - cron: '0 4 * * *'  # 运行于每天UTC 4:00 (相当于Halifax时间午夜0:00)
  workflow_dispatch:  # 允许手动触发

jobs:
  update-weather:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests
    
    - name: Run weather update script
      env:
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      run: python canada_weather.py
    
    - name: Commit changes
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git pull origin main --rebase
        git add canada_weather.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update weather data" && git push)
