name: Daily Weather Update

on:
  schedule:
    - cron: '0 4 * * *'  # 运行于每天UTC 4:00 (相当于Halifax时间午夜0:00)
  workflow_dispatch:  # 允许手动触发

jobs:
  update-weather:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 获取完整历史以便进行提交
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run weather update script
      env:
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      run: python halifax_weather.py
      
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add halifax_weather.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update weather data [skip ci]" && git push)
